### ISSUE TITLE
hyperUnique returning 0

### ISSUE THREAD

**Issue by l15k4** [implydata/pivot#118]
Hey,

hyperUnique aggregation only works in Pivot if you index it this way: 

```
 {
    "type" : "hyperUnique",
    "name" : "foo",
    "fieldName" : "foo"
  }
```

But if you do : 

```
 {
    "type" : "hyperUnique",
    "name" : "bar",
    "fieldName" : "foo"
  }
```

then the query is :  

```
 {
    "type" : "hyperUnique",
    "name" : "foo",
    "fieldName" : "foo"
  }
```

But the actual HLL fieldName is `bar`, not foo...

I'm using the last `distribution-docker` ...  Is it best practice to name it the same as the original indexed field ?

**Comment by vogievetsky** [comment]
Pivot should be able to rename things arbitrarily. Looking into this.

**Comment by turu** [comment]
+1 to fixing this issue. It is blocking us from using Pivot to its full potential.

**Comment by turu** [comment]
We've managed to work around this issue by using a custom configuration along the lines of:
```yaml
    attributeOverrides:
      - name: UNIQUE_FIELD_NAME
        type: STRING
        special: unique

    options:
      customAggregations:
        customUnique:
          aggregation:
            type: hyperUnique
            fieldName: UNIQUE_METRIC_NAME

    measures:
      - name: UNIQUES
        expression: $main.custom(customUnique)
```
