### ISSUE TITLE
Queryable data source

### ISSUE THREAD

**Issue by venukb** [implydata/pivot#28]
I have 6 data sources and all 6 are configured in config.yaml. With newer version, I see a log saying 4 are queryable and only those 4 show up in UI.
Even though the other 2 data sources don't have data in recent 2 weeks, still want to use pivot to query/visualize data.
How to get this going?

**Comment by vogievetsky** [comment]
Hi, it is currently impossible to get those 2 datasources to show up in the current version of Pivot. I will add a `disableIntrospect` flag to allow you to configure it. Will update/close this issue when added.

**Comment by vogievetsky** [comment]
hi, I have added a flag in the latest version.

Try pulling and set `skipIntrospection` to `true` in the `options` for the two dataSources in question.

Here is an example of how it might look like in a config:

```yaml
  - name: wiki
    title: Wikipedia Edits
    engine: druid
    source: wikipedia

    timeAttribute: time

    options:
      # Avoid doing an introspect
      skipIntrospection: true

    # All the dimensions will be automatically filled in from the data source
    dimensions:
      - name: time
        type: TIME
```

Closing the issue, please re-open if it does not work.
