### ISSUE TITLE
Identify countDistinct / HLL automatically

### ISSUE THREAD

**Issue by vidma** [implydata/pivot#54]
maybe I don't know how to do it correctly, but this is the only way I was able to countDistinct / HLL work:
```yml
    # other simple measures are discovered automatically
    # but for count-distincts, looks like this nasty extra indirection is needed
    # otherwise, it always displays 0.0
    options:
      customAggregations:
        unique_sellers_custom:
          aggregation:
            type: hyperUnique
            fieldName: sellers

    measures:
      - name: sellers
        expression: $main.custom(unique_sellers_custom)
```

another issue, is how to make more complex HLL aggregations work, like this druid query:
```yml
{
  "type": "cardinality",
  "name": "unique_buyers_or_sellers",
  "fieldNames": [ "seller_id_hll", “buyer_id_hll" ]
}
```
